env:
  - CORS_WHITELIST_URL="http://scrum-app-local.com:4000 http://scrum-app-local.com:3000 http://localhost:4000 http://localhost:3000"
language: node_js
node_js:
  - 10.16
notifications:
  email: false
