const ACTIONS_FETCH = 'FETCH';
const ACTIONS_POST = 'POST';
const ACTIONS_FAILURE = 'FAILURE';
const ACTIONS_SUCCESS = 'SUCCESS';
const LIBRARY_ROOT = 'SCRUM';
const ROUTE_CHANGED = 'ROUTE_CHANGED';

export {
  ACTIONS_FETCH,
  ACTIONS_POST,
  ACTIONS_FAILURE,
  ACTIONS_SUCCESS,
  LIBRARY_ROOT,
  ROUTE_CHANGED,
};
